### PR TITLE
feat #189 - Add args to specify folder location of slides and labs

### PR DESCRIPTION
**Pull request by Nebulis**
feat #189 - Add args to specify folder location of slides and labs

### CODE REVIEW

**Comment by jlandure** [comment]
@Nebulis is it for an english related problem?

**Comment by Nebulis** [comment]
Yeah, Looks like the common strategy to translate slides is to put them into a different folder (Slides_en) but with last version of framework we cannot serve that files neither create the pdf

**Comment by hgwood** [comment]
Simple and straight-forward. Great work, thanks!

**Comment by hgwood** [comment]
Published in 2.6.0.

**Pull request merged**
